= Red Hat Data Grid 8 embedded mode
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2021-01
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]
// End: Enable admonition icons

This repository contains a demo of Red Hat Data Grid 8 in Embedded mode (previously Library mode). It also contains all the Openshift resources to deploy the code easily.

Some of the sections of the documentation and Java code are based on the official examples of Infinispan and Data Grid public repositories. Check the following repositories: https://github.com/redhat-developer/redhat-datagrid-tutorials[DG Tutorials] and https://github.com/infinispan/infinispan-simple-tutorials[Infinispan Simple Tutorials].

// Create the Table of contents here
toc::[]

== Introduction

Red Hat Data Grid is an in-memory, distributed, NoSQL datastore solution. Your applications can access, process, and analyze data at in-memory speed to deliver a superior user experience. You can use Red Hat Data Grid in two modes:

* Library (Embedded) Mode provides binaries to build and deploy custom runtime environments. RHDG runs alongside your application in the same JVM. Your application has local access to a single node in a distributed cluster.

* Remote Client-Server Mode provides a self-contained process in a container based on JBoss EAP. RHDG runs remotely and provides access to data through Hot Rod, REST, or CLI interfaces.

In this repository, we are going to focus on the first mode: Embedded. For more applications and configuration examples of the Remote client-server mode, please check this https://github.com/alvarolop/rhdg8-server[repository].


== Running the application

You can run this application locally or on OCP.


=== Running the application locally

Running your application is as simple as running any other Spring Boot application. The only issue here is that you will need more than one instance running on localhost, and therefore, you might have port collisions. Use the following command to run two instances simultaneously in different terminal windows:

[source, bash]
----
$ mvn clean package
$ java -jar -Dserver.port=8090 target/rhdg-embedded-1.0.0.jar
$ java -jar -Dserver.port=8091 target/rhdg-embedded-1.0.0.jar
----


=== Deploying the application on OCP

Deploying your client application on OCP requires to create several Openshift objects. Therefore, we are going to define some common variables that will be used from now onwards:

[source, bash]
----
export APP_NAME=rhdg
export NAMESPACE=rhdg8-embedded
export GIT_REPO=https://github.com/alvarolop/rhdg8-embedded.git
----

First, create a project to host the application:
[source, bash]
----
oc new-project $NAMESPACE --display-name="RHDG 8 - Embedded" --description="This project contains an application with an embedded DataGrid cluster"
----


Second, create a ConfigMap that will store your application configuration:
[source, bash]
----
oc create configmap ${APP_NAME}-config \
--from-file=infinispan.xml=src/main/resources/infinispan-k8s.xml \
--from-file=application.properties=src/main/resources/application-k8s.properties \
--from-file=logback-spring.xml=src/main/resources/logback-spring-k8s.xml -n $NAMESPACE
----

Third, use an Openshift template to create your Openshift resources. This is the command to apply the template on your cluster:
[source, bash]
----
oc process -f templates/rhdg-embedded.yaml -p APPLICATION_NAME=$APP_NAME -p GIT_REPOSITORY=$GIT_REPO -p APP_NAMESPACE=$NAMESPACE | oc apply -f -
----

== Annex: Migrating to RHDG 8.3

=== Migrating annotations to Hibernate 6

It is important to notice that upgrading your application to RHDG 3.0 means upgrading to Hibernate 6. In this new version, some annotations have been deprecated. Use the following https://docs.jboss.org/hibernate/search/6.0/migration/html_single/#field[link] to migrate your annotations to the new ones. Check the https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#mapper-orm-directfieldmapping-annotations[following section] to understand the difference between `@GenericField`, `@FullTextField`, and `@KeywordField`.

* `@Indexed` https://docs.jboss.org/hibernate/search/6.0/migration/html_single/#indexed-basics[is still available] in Hibernate Search 6, but moved to a different package: `org.hibernate.search.mapper.pojo.mapping.definition.annotation.Indexed`.

* `@DateBridge` https://docs.jboss.org/hibernate/search/6.0/migration/html_single/#datebridge[is not necessary] to index Date values: you can simply apply `@GenericField` to a property of type `java.util.Date`, `java.sql.Date`, `java.sql.Time` or `java.sql.Timestamp`, and an appropriate default bridge will be used.


Check the https://infinispan.org/docs/dev/titles/developing/developing.html#embedded_query_example[configuration examples] with the new annotations for RHDG 8.3.

=== Migrating indexing configuration

Change how to configure Local Heap storage of the Indexes. https://infinispan.org/docs/dev/titles/upgrading/upgrading.html#storage[Link].


== Useful links

* https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.1/html-single/data_grid_library_mode/indexÞ[Documentation: DG Library mode].
* https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.1/html-single/data_grid_spring_boot_starter/index#sb_starter_embedded[Documentation: SB starter for library mode].
