apiVersion: v1
kind: Template
metadata:
  name: rhdg8-client
  annotations:
    description: Template to deploy a Java client application to connecto to a RHDG cluster on OCP.
    tags: infinispan,datagrid,java,springboot
    iconClass: icon-rh-openjdk
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
labels:
  template: rhdg8-client
objects:



- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${APP_NAMESPACE}
  spec:
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPOSITORY}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ubi8-openjdk-11:1.3
          namespace: openshift
      type: Source
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    triggers:
      - type: ConfigChange
      - type: ImageChange


parameters:
  - name: APPLICATION_NAME
    description: "The name of the application."
    required: true
  - name: APP_NAMESPACE
    description: "The namespace of the application."
    required: true
  - name: MOUNT_PATH
    description: "The path where the configuration file of the application is mounted."
    value: "/deployments/config"
    required: true
  - name: GIT_REPOSITORY
    description: "The git repository of the application."
    required: true
  - name: RHDG_CLUSTER_NAME
    description: "The name of the cluster that this client will connect to. It is needed to automatically configure ssl."
    value: "rhdg"
    required: false